apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: appset
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  sourceRepos:
    - "https://github.com/yair-segal/ArgoCDRollouts.git"
  destinations:
    - namespace: default
      server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
    - group: 'apps'
      kind: Deployment
    - group: 'apps'
      kind: ReplicaSet
    - group: ''
      kind: Pod
